// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: api/refiner.proto

package refinerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RefinerService_Refine_FullMethodName = "/refiner.v1.RefinerService/Refine"
	RefinerService_PageIn_FullMethodName = "/refiner.v1.RefinerService/PageIn"
)

// RefinerServiceClient is the client API for RefinerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RefinerServiceClient interface {
	Refine(ctx context.Context, in *RefineRequest, opts ...grpc.CallOption) (*RefineResponse, error)
	PageIn(ctx context.Context, in *PageInRequest, opts ...grpc.CallOption) (*PageInResponse, error)
}

type refinerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRefinerServiceClient(cc grpc.ClientConnInterface) RefinerServiceClient {
	return &refinerServiceClient{cc}
}

func (c *refinerServiceClient) Refine(ctx context.Context, in *RefineRequest, opts ...grpc.CallOption) (*RefineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefineResponse)
	err := c.cc.Invoke(ctx, RefinerService_Refine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refinerServiceClient) PageIn(ctx context.Context, in *PageInRequest, opts ...grpc.CallOption) (*PageInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageInResponse)
	err := c.cc.Invoke(ctx, RefinerService_PageIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefinerServiceServer is the server API for RefinerService service.
// All implementations must embed UnimplementedRefinerServiceServer
// for forward compatibility.
type RefinerServiceServer interface {
	Refine(context.Context, *RefineRequest) (*RefineResponse, error)
	PageIn(context.Context, *PageInRequest) (*PageInResponse, error)
	mustEmbedUnimplementedRefinerServiceServer()
}

// UnimplementedRefinerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRefinerServiceServer struct{}

func (UnimplementedRefinerServiceServer) Refine(context.Context, *RefineRequest) (*RefineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refine not implemented")
}
func (UnimplementedRefinerServiceServer) PageIn(context.Context, *PageInRequest) (*PageInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PageIn not implemented")
}
func (UnimplementedRefinerServiceServer) mustEmbedUnimplementedRefinerServiceServer() {}
func (UnimplementedRefinerServiceServer) testEmbeddedByValue()                        {}

// UnsafeRefinerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RefinerServiceServer will
// result in compilation errors.
type UnsafeRefinerServiceServer interface {
	mustEmbedUnimplementedRefinerServiceServer()
}

func RegisterRefinerServiceServer(s grpc.ServiceRegistrar, srv RefinerServiceServer) {
	// If the following call panics, it indicates UnimplementedRefinerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RefinerService_ServiceDesc, srv)
}

func _RefinerService_Refine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefinerServiceServer).Refine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefinerService_Refine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefinerServiceServer).Refine(ctx, req.(*RefineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefinerService_PageIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefinerServiceServer).PageIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefinerService_PageIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefinerServiceServer).PageIn(ctx, req.(*PageInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RefinerService_ServiceDesc is the grpc.ServiceDesc for RefinerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RefinerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "refiner.v1.RefinerService",
	HandlerType: (*RefinerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Refine",
			Handler:    _RefinerService_Refine_Handler,
		},
		{
			MethodName: "PageIn",
			Handler:    _RefinerService_PageIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/refiner.proto",
}
