// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/refiner.proto

package refinerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FragmentType int32

const (
	FragmentType_FRAGMENT_TYPE_UNSPECIFIED FragmentType = 0
	FragmentType_FRAGMENT_TYPE_TITLE       FragmentType = 1
	FragmentType_FRAGMENT_TYPE_BODY        FragmentType = 2
	FragmentType_FRAGMENT_TYPE_CODE        FragmentType = 3
	FragmentType_FRAGMENT_TYPE_TABLE       FragmentType = 4
	FragmentType_FRAGMENT_TYPE_JSON        FragmentType = 5
	FragmentType_FRAGMENT_TYPE_TOOL_OUTPUT FragmentType = 6
	FragmentType_FRAGMENT_TYPE_LOG         FragmentType = 7
	FragmentType_FRAGMENT_TYPE_ERROR_STACK FragmentType = 8
)

// Enum value maps for FragmentType.
var (
	FragmentType_name = map[int32]string{
		0: "FRAGMENT_TYPE_UNSPECIFIED",
		1: "FRAGMENT_TYPE_TITLE",
		2: "FRAGMENT_TYPE_BODY",
		3: "FRAGMENT_TYPE_CODE",
		4: "FRAGMENT_TYPE_TABLE",
		5: "FRAGMENT_TYPE_JSON",
		6: "FRAGMENT_TYPE_TOOL_OUTPUT",
		7: "FRAGMENT_TYPE_LOG",
		8: "FRAGMENT_TYPE_ERROR_STACK",
	}
	FragmentType_value = map[string]int32{
		"FRAGMENT_TYPE_UNSPECIFIED": 0,
		"FRAGMENT_TYPE_TITLE":       1,
		"FRAGMENT_TYPE_BODY":        2,
		"FRAGMENT_TYPE_CODE":        3,
		"FRAGMENT_TYPE_TABLE":       4,
		"FRAGMENT_TYPE_JSON":        5,
		"FRAGMENT_TYPE_TOOL_OUTPUT": 6,
		"FRAGMENT_TYPE_LOG":         7,
		"FRAGMENT_TYPE_ERROR_STACK": 8,
	}
)

func (x FragmentType) Enum() *FragmentType {
	p := new(FragmentType)
	*p = x
	return p
}

func (x FragmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FragmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_refiner_proto_enumTypes[0].Descriptor()
}

func (FragmentType) Type() protoreflect.EnumType {
	return &file_api_refiner_proto_enumTypes[0]
}

func (x FragmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FragmentType.Descriptor instead.
func (FragmentType) EnumDescriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_refiner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RagFragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FragmentType           `protobuf:"varint,1,opt,name=type,proto3,enum=refiner.v1.FragmentType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagFragment) Reset() {
	*x = RagFragment{}
	mi := &file_api_refiner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagFragment) ProtoMessage() {}

func (x *RagFragment) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagFragment.ProtoReflect.Descriptor instead.
func (*RagFragment) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{1}
}

func (x *RagFragment) GetType() FragmentType {
	if x != nil {
		return x.Type
	}
	return FragmentType_FRAGMENT_TYPE_UNSPECIFIED
}

func (x *RagFragment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RagFragment) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type RagChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Fragments     []*RagFragment         `protobuf:"bytes,4,rep,name=fragments,proto3" json:"fragments,omitempty"`
	Sources       []string               `protobuf:"bytes,5,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagChunk) Reset() {
	*x = RagChunk{}
	mi := &file_api_refiner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagChunk) ProtoMessage() {}

func (x *RagChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagChunk.ProtoReflect.Descriptor instead.
func (*RagChunk) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{2}
}

func (x *RagChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RagChunk) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RagChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RagChunk) GetFragments() []*RagFragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

func (x *RagChunk) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type PagedChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	PageKeys      []string               `protobuf:"bytes,2,rep,name=page_keys,json=pageKeys,proto3" json:"page_keys,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagedChunk) Reset() {
	*x = PagedChunk{}
	mi := &file_api_refiner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagedChunk) ProtoMessage() {}

func (x *PagedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagedChunk.ProtoReflect.Descriptor instead.
func (*PagedChunk) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{3}
}

func (x *PagedChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *PagedChunk) GetPageKeys() []string {
	if x != nil {
		return x.PageKeys
	}
	return nil
}

func (x *PagedChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PagedChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ModelConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Model            string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	MaxContextTokens int32                  `protobuf:"varint,2,opt,name=max_context_tokens,json=maxContextTokens,proto3" json:"max_context_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelConfig) Reset() {
	*x = ModelConfig{}
	mi := &file_api_refiner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConfig) ProtoMessage() {}

func (x *ModelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelConfig.ProtoReflect.Descriptor instead.
func (*ModelConfig) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{4}
}

func (x *ModelConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelConfig) GetMaxContextTokens() int32 {
	if x != nil {
		return x.MaxContextTokens
	}
	return 0
}

type RefineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	RagChunks     []*RagChunk            `protobuf:"bytes,2,rep,name=rag_chunks,json=ragChunks,proto3" json:"rag_chunks,omitempty"`
	Model         *ModelConfig           `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	TokenBudget   int32                  `protobuf:"varint,4,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"`
	Policy        string                 `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefineRequest) Reset() {
	*x = RefineRequest{}
	mi := &file_api_refiner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineRequest) ProtoMessage() {}

func (x *RefineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineRequest.ProtoReflect.Descriptor instead.
func (*RefineRequest) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{5}
}

func (x *RefineRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *RefineRequest) GetRagChunks() []*RagChunk {
	if x != nil {
		return x.RagChunks
	}
	return nil
}

func (x *RefineRequest) GetModel() *ModelConfig {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *RefineRequest) GetTokenBudget() int32 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

func (x *RefineRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *RefineRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RefineRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ProcessorCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Aggressive          bool                   `protobuf:"varint,1,opt,name=aggressive,proto3" json:"aggressive,omitempty"`
	Lossy               bool                   `protobuf:"varint,2,opt,name=lossy,proto3" json:"lossy,omitempty"`
	StructuredInputOnly bool                   `protobuf:"varint,3,opt,name=structured_input_only,json=structuredInputOnly,proto3" json:"structured_input_only,omitempty"`
	MinTriggerTokens    int32                  `protobuf:"varint,4,opt,name=min_trigger_tokens,json=minTriggerTokens,proto3" json:"min_trigger_tokens,omitempty"`
	PreserveCitation    bool                   `protobuf:"varint,5,opt,name=preserve_citation,json=preserveCitation,proto3" json:"preserve_citation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessorCapabilities) Reset() {
	*x = ProcessorCapabilities{}
	mi := &file_api_refiner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorCapabilities) ProtoMessage() {}

func (x *ProcessorCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorCapabilities.ProtoReflect.Descriptor instead.
func (*ProcessorCapabilities) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessorCapabilities) GetAggressive() bool {
	if x != nil {
		return x.Aggressive
	}
	return false
}

func (x *ProcessorCapabilities) GetLossy() bool {
	if x != nil {
		return x.Lossy
	}
	return false
}

func (x *ProcessorCapabilities) GetStructuredInputOnly() bool {
	if x != nil {
		return x.StructuredInputOnly
	}
	return false
}

func (x *ProcessorCapabilities) GetMinTriggerTokens() int32 {
	if x != nil {
		return x.MinTriggerTokens
	}
	return 0
}

func (x *ProcessorCapabilities) GetPreserveCitation() bool {
	if x != nil {
		return x.PreserveCitation
	}
	return false
}

type StepSemanticAudit struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Removed             []string               `protobuf:"bytes,1,rep,name=removed,proto3" json:"removed,omitempty"`
	Retained            []string               `protobuf:"bytes,2,rep,name=retained,proto3" json:"retained,omitempty"`
	Reasons             []string               `protobuf:"bytes,3,rep,name=reasons,proto3" json:"reasons,omitempty"`
	SourcePreserved     bool                   `protobuf:"varint,4,opt,name=source_preserved,json=sourcePreserved,proto3" json:"source_preserved,omitempty"`
	CodeFencePreserved  bool                   `protobuf:"varint,5,opt,name=code_fence_preserved,json=codeFencePreserved,proto3" json:"code_fence_preserved,omitempty"`
	ErrorStackPreserved bool                   `protobuf:"varint,6,opt,name=error_stack_preserved,json=errorStackPreserved,proto3" json:"error_stack_preserved,omitempty"`
	DroppedCitations    int32                  `protobuf:"varint,7,opt,name=dropped_citations,json=droppedCitations,proto3" json:"dropped_citations,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StepSemanticAudit) Reset() {
	*x = StepSemanticAudit{}
	mi := &file_api_refiner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepSemanticAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepSemanticAudit) ProtoMessage() {}

func (x *StepSemanticAudit) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepSemanticAudit.ProtoReflect.Descriptor instead.
func (*StepSemanticAudit) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{7}
}

func (x *StepSemanticAudit) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *StepSemanticAudit) GetRetained() []string {
	if x != nil {
		return x.Retained
	}
	return nil
}

func (x *StepSemanticAudit) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *StepSemanticAudit) GetSourcePreserved() bool {
	if x != nil {
		return x.SourcePreserved
	}
	return false
}

func (x *StepSemanticAudit) GetCodeFencePreserved() bool {
	if x != nil {
		return x.CodeFencePreserved
	}
	return false
}

func (x *StepSemanticAudit) GetErrorStackPreserved() bool {
	if x != nil {
		return x.ErrorStackPreserved
	}
	return false
}

func (x *StepSemanticAudit) GetDroppedCitations() int32 {
	if x != nil {
		return x.DroppedCitations
	}
	return 0
}

type StepAudit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BeforeTokens  int32                  `protobuf:"varint,2,opt,name=before_tokens,json=beforeTokens,proto3" json:"before_tokens,omitempty"`
	AfterTokens   int32                  `protobuf:"varint,3,opt,name=after_tokens,json=afterTokens,proto3" json:"after_tokens,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  *ProcessorCapabilities `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Semantic      *StepSemanticAudit     `protobuf:"bytes,7,opt,name=semantic,proto3" json:"semantic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepAudit) Reset() {
	*x = StepAudit{}
	mi := &file_api_refiner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepAudit) ProtoMessage() {}

func (x *StepAudit) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepAudit.ProtoReflect.Descriptor instead.
func (*StepAudit) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{8}
}

func (x *StepAudit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepAudit) GetBeforeTokens() int32 {
	if x != nil {
		return x.BeforeTokens
	}
	return 0
}

func (x *StepAudit) GetAfterTokens() int32 {
	if x != nil {
		return x.AfterTokens
	}
	return 0
}

func (x *StepAudit) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepAudit) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *StepAudit) GetCapabilities() *ProcessorCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *StepAudit) GetSemantic() *StepSemanticAudit {
	if x != nil {
		return x.Semantic
	}
	return nil
}

type RefineResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OptimizedPrompt      string                 `protobuf:"bytes,1,opt,name=optimized_prompt,json=optimizedPrompt,proto3" json:"optimized_prompt,omitempty"`
	InputTokens          int32                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens         int32                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	Audits               []*StepAudit           `protobuf:"bytes,4,rep,name=audits,proto3" json:"audits,omitempty"`
	PagedChunks          []*PagedChunk          `protobuf:"bytes,5,rep,name=paged_chunks,json=pagedChunks,proto3" json:"paged_chunks,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BudgetMet            bool                   `protobuf:"varint,7,opt,name=budget_met,json=budgetMet,proto3" json:"budget_met,omitempty"`
	PendingSummaryJobIds []string               `protobuf:"bytes,8,rep,name=pending_summary_job_ids,json=pendingSummaryJobIds,proto3" json:"pending_summary_job_ids,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RefineResponse) Reset() {
	*x = RefineResponse{}
	mi := &file_api_refiner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineResponse) ProtoMessage() {}

func (x *RefineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineResponse.ProtoReflect.Descriptor instead.
func (*RefineResponse) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{9}
}

func (x *RefineResponse) GetOptimizedPrompt() string {
	if x != nil {
		return x.OptimizedPrompt
	}
	return ""
}

func (x *RefineResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *RefineResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *RefineResponse) GetAudits() []*StepAudit {
	if x != nil {
		return x.Audits
	}
	return nil
}

func (x *RefineResponse) GetPagedChunks() []*PagedChunk {
	if x != nil {
		return x.PagedChunks
	}
	return nil
}

func (x *RefineResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RefineResponse) GetBudgetMet() bool {
	if x != nil {
		return x.BudgetMet
	}
	return false
}

func (x *RefineResponse) GetPendingSummaryJobIds() []string {
	if x != nil {
		return x.PendingSummaryJobIds
	}
	return nil
}

type PageInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageKeys      []string               `protobuf:"bytes,1,rep,name=page_keys,json=pageKeys,proto3" json:"page_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInRequest) Reset() {
	*x = PageInRequest{}
	mi := &file_api_refiner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInRequest) ProtoMessage() {}

func (x *PageInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInRequest.ProtoReflect.Descriptor instead.
func (*PageInRequest) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{10}
}

func (x *PageInRequest) GetPageKeys() []string {
	if x != nil {
		return x.PageKeys
	}
	return nil
}

type SummaryArtifact struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId      string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Policy          string                 `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	ChunkId         string                 `protobuf:"bytes,6,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Source          string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	PageRefs        []string               `protobuf:"bytes,8,rep,name=page_refs,json=pageRefs,proto3" json:"page_refs,omitempty"`
	ContentHash     string                 `protobuf:"bytes,9,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	SummaryText     string                 `protobuf:"bytes,10,opt,name=summary_text,json=summaryText,proto3" json:"summary_text,omitempty"`
	FragmentTypes   []string               `protobuf:"bytes,11,rep,name=fragment_types,json=fragmentTypes,proto3" json:"fragment_types,omitempty"`
	Provider        string                 `protobuf:"bytes,12,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderVersion string                 `protobuf:"bytes,13,opt,name=provider_version,json=providerVersion,proto3" json:"provider_version,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,14,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SummaryArtifact) Reset() {
	*x = SummaryArtifact{}
	mi := &file_api_refiner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryArtifact) ProtoMessage() {}

func (x *SummaryArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryArtifact.ProtoReflect.Descriptor instead.
func (*SummaryArtifact) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{11}
}

func (x *SummaryArtifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *SummaryArtifact) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SummaryArtifact) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SummaryArtifact) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SummaryArtifact) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *SummaryArtifact) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SummaryArtifact) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SummaryArtifact) GetPageRefs() []string {
	if x != nil {
		return x.PageRefs
	}
	return nil
}

func (x *SummaryArtifact) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *SummaryArtifact) GetSummaryText() string {
	if x != nil {
		return x.SummaryText
	}
	return ""
}

func (x *SummaryArtifact) GetFragmentTypes() []string {
	if x != nil {
		return x.FragmentTypes
	}
	return nil
}

func (x *SummaryArtifact) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SummaryArtifact) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

func (x *SummaryArtifact) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SummaryArtifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SummaryArtifact) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type StoredPage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsSummary       bool                   `protobuf:"varint,3,opt,name=is_summary,json=isSummary,proto3" json:"is_summary,omitempty"`
	SummaryJobId    string                 `protobuf:"bytes,4,opt,name=summary_job_id,json=summaryJobId,proto3" json:"summary_job_id,omitempty"`
	SummaryArtifact *SummaryArtifact       `protobuf:"bytes,5,opt,name=summary_artifact,json=summaryArtifact,proto3" json:"summary_artifact,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoredPage) Reset() {
	*x = StoredPage{}
	mi := &file_api_refiner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredPage) ProtoMessage() {}

func (x *StoredPage) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredPage.ProtoReflect.Descriptor instead.
func (*StoredPage) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{12}
}

func (x *StoredPage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoredPage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoredPage) GetIsSummary() bool {
	if x != nil {
		return x.IsSummary
	}
	return false
}

func (x *StoredPage) GetSummaryJobId() string {
	if x != nil {
		return x.SummaryJobId
	}
	return ""
}

func (x *StoredPage) GetSummaryArtifact() *SummaryArtifact {
	if x != nil {
		return x.SummaryArtifact
	}
	return nil
}

type PageInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*StoredPage          `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInResponse) Reset() {
	*x = PageInResponse{}
	mi := &file_api_refiner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInResponse) ProtoMessage() {}

func (x *PageInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_refiner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInResponse.ProtoReflect.Descriptor instead.
func (*PageInResponse) Descriptor() ([]byte, []int) {
	return file_api_refiner_proto_rawDescGZIP(), []int{13}
}

func (x *PageInResponse) GetPages() []*StoredPage {
	if x != nil {
		return x.Pages
	}
	return nil
}

var File_api_refiner_proto protoreflect.FileDescriptor

const file_api_refiner_proto_rawDesc = "" +
	"\n" +
	"\x11api/refiner.proto\x12\n" +
	"refiner.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"q\n" +
	"\vRagFragment\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.refiner.v1.FragmentTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"\x9d\x01\n" +
	"\bRagChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x125\n" +
	"\tfragments\x18\x04 \x03(\v2\x17.refiner.v1.RagFragmentR\tfragments\x12\x18\n" +
	"\asources\x18\x05 \x03(\tR\asources\"\x82\x01\n" +
	"\n" +
	"PagedChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1b\n" +
	"\tpage_keys\x18\x02 \x03(\tR\bpageKeys\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"Q\n" +
	"\vModelConfig\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12,\n" +
	"\x12max_context_tokens\x18\x02 \x01(\x05R\x10maxContextTokens\"\x9d\x02\n" +
	"\rRefineRequest\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.refiner.v1.MessageR\bmessages\x123\n" +
	"\n" +
	"rag_chunks\x18\x02 \x03(\v2\x14.refiner.v1.RagChunkR\tragChunks\x12-\n" +
	"\x05model\x18\x03 \x01(\v2\x17.refiner.v1.ModelConfigR\x05model\x12!\n" +
	"\ftoken_budget\x18\x04 \x01(\x05R\vtokenBudget\x12\x16\n" +
	"\x06policy\x18\x05 \x01(\tR\x06policy\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\xdc\x01\n" +
	"\x15ProcessorCapabilities\x12\x1e\n" +
	"\n" +
	"aggressive\x18\x01 \x01(\bR\n" +
	"aggressive\x12\x14\n" +
	"\x05lossy\x18\x02 \x01(\bR\x05lossy\x122\n" +
	"\x15structured_input_only\x18\x03 \x01(\bR\x13structuredInputOnly\x12,\n" +
	"\x12min_trigger_tokens\x18\x04 \x01(\x05R\x10minTriggerTokens\x12+\n" +
	"\x11preserve_citation\x18\x05 \x01(\bR\x10preserveCitation\"\xa1\x02\n" +
	"\x11StepSemanticAudit\x12\x18\n" +
	"\aremoved\x18\x01 \x03(\tR\aremoved\x12\x1a\n" +
	"\bretained\x18\x02 \x03(\tR\bretained\x12\x18\n" +
	"\areasons\x18\x03 \x03(\tR\areasons\x12)\n" +
	"\x10source_preserved\x18\x04 \x01(\bR\x0fsourcePreserved\x120\n" +
	"\x14code_fence_preserved\x18\x05 \x01(\bR\x12codeFencePreserved\x122\n" +
	"\x15error_stack_preserved\x18\x06 \x01(\bR\x13errorStackPreserved\x12+\n" +
	"\x11dropped_citations\x18\a \x01(\x05R\x10droppedCitations\"\x84\x03\n" +
	"\tStepAudit\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rbefore_tokens\x18\x02 \x01(\x05R\fbeforeTokens\x12!\n" +
	"\fafter_tokens\x18\x03 \x01(\x05R\vafterTokens\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12<\n" +
	"\adetails\x18\x05 \x03(\v2\".refiner.v1.StepAudit.DetailsEntryR\adetails\x12E\n" +
	"\fcapabilities\x18\x06 \x01(\v2!.refiner.v1.ProcessorCapabilitiesR\fcapabilities\x129\n" +
	"\bsemantic\x18\a \x01(\v2\x1d.refiner.v1.StepSemanticAuditR\bsemantic\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x03\n" +
	"\x0eRefineResponse\x12)\n" +
	"\x10optimized_prompt\x18\x01 \x01(\tR\x0foptimizedPrompt\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x05R\foutputTokens\x12-\n" +
	"\x06audits\x18\x04 \x03(\v2\x15.refiner.v1.StepAuditR\x06audits\x129\n" +
	"\fpaged_chunks\x18\x05 \x03(\v2\x16.refiner.v1.PagedChunkR\vpagedChunks\x12D\n" +
	"\bmetadata\x18\x06 \x03(\v2(.refiner.v1.RefineResponse.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"budget_met\x18\a \x01(\bR\tbudgetMet\x125\n" +
	"\x17pending_summary_job_ids\x18\b \x03(\tR\x14pendingSummaryJobIds\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\rPageInRequest\x12\x1b\n" +
	"\tpage_keys\x18\x01 \x03(\tR\bpageKeys\"\xc0\x04\n" +
	"\x0fSummaryArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x16\n" +
	"\x06policy\x18\x05 \x01(\tR\x06policy\x12\x19\n" +
	"\bchunk_id\x18\x06 \x01(\tR\achunkId\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1b\n" +
	"\tpage_refs\x18\b \x03(\tR\bpageRefs\x12!\n" +
	"\fcontent_hash\x18\t \x01(\tR\vcontentHash\x12!\n" +
	"\fsummary_text\x18\n" +
	" \x01(\tR\vsummaryText\x12%\n" +
	"\x0efragment_types\x18\v \x03(\tR\rfragmentTypes\x12\x1a\n" +
	"\bprovider\x18\f \x01(\tR\bprovider\x12)\n" +
	"\x10provider_version\x18\r \x01(\tR\x0fproviderVersion\x12%\n" +
	"\x0eschema_version\x18\x0e \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xc5\x01\n" +
	"\n" +
	"StoredPage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"is_summary\x18\x03 \x01(\bR\tisSummary\x12$\n" +
	"\x0esummary_job_id\x18\x04 \x01(\tR\fsummaryJobId\x12F\n" +
	"\x10summary_artifact\x18\x05 \x01(\v2\x1b.refiner.v1.SummaryArtifactR\x0fsummaryArtifact\">\n" +
	"\x0ePageInResponse\x12,\n" +
	"\x05pages\x18\x01 \x03(\v2\x16.refiner.v1.StoredPageR\x05pages*\xfc\x01\n" +
	"\fFragmentType\x12\x1d\n" +
	"\x19FRAGMENT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FRAGMENT_TYPE_TITLE\x10\x01\x12\x16\n" +
	"\x12FRAGMENT_TYPE_BODY\x10\x02\x12\x16\n" +
	"\x12FRAGMENT_TYPE_CODE\x10\x03\x12\x17\n" +
	"\x13FRAGMENT_TYPE_TABLE\x10\x04\x12\x16\n" +
	"\x12FRAGMENT_TYPE_JSON\x10\x05\x12\x1d\n" +
	"\x19FRAGMENT_TYPE_TOOL_OUTPUT\x10\x06\x12\x15\n" +
	"\x11FRAGMENT_TYPE_LOG\x10\a\x12\x1d\n" +
	"\x19FRAGMENT_TYPE_ERROR_STACK\x10\b2\x92\x01\n" +
	"\x0eRefinerService\x12?\n" +
	"\x06Refine\x12\x19.refiner.v1.RefineRequest\x1a\x1a.refiner.v1.RefineResponse\x12?\n" +
	"\x06PageIn\x12\x19.refiner.v1.PageInRequest\x1a\x1a.refiner.v1.PageInResponseB)Z'context-refiner/api/refinerv1;refinerv1b\x06proto3"

var (
	file_api_refiner_proto_rawDescOnce sync.Once
	file_api_refiner_proto_rawDescData []byte
)

func file_api_refiner_proto_rawDescGZIP() []byte {
	file_api_refiner_proto_rawDescOnce.Do(func() {
		file_api_refiner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_refiner_proto_rawDesc), len(file_api_refiner_proto_rawDesc)))
	})
	return file_api_refiner_proto_rawDescData
}

var file_api_refiner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_refiner_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_refiner_proto_goTypes = []any{
	(FragmentType)(0),             // 0: refiner.v1.FragmentType
	(*Message)(nil),               // 1: refiner.v1.Message
	(*RagFragment)(nil),           // 2: refiner.v1.RagFragment
	(*RagChunk)(nil),              // 3: refiner.v1.RagChunk
	(*PagedChunk)(nil),            // 4: refiner.v1.PagedChunk
	(*ModelConfig)(nil),           // 5: refiner.v1.ModelConfig
	(*RefineRequest)(nil),         // 6: refiner.v1.RefineRequest
	(*ProcessorCapabilities)(nil), // 7: refiner.v1.ProcessorCapabilities
	(*StepSemanticAudit)(nil),     // 8: refiner.v1.StepSemanticAudit
	(*StepAudit)(nil),             // 9: refiner.v1.StepAudit
	(*RefineResponse)(nil),        // 10: refiner.v1.RefineResponse
	(*PageInRequest)(nil),         // 11: refiner.v1.PageInRequest
	(*SummaryArtifact)(nil),       // 12: refiner.v1.SummaryArtifact
	(*StoredPage)(nil),            // 13: refiner.v1.StoredPage
	(*PageInResponse)(nil),        // 14: refiner.v1.PageInResponse
	nil,                           // 15: refiner.v1.StepAudit.DetailsEntry
	nil,                           // 16: refiner.v1.RefineResponse.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_api_refiner_proto_depIdxs = []int32{
	0,  // 0: refiner.v1.RagFragment.type:type_name -> refiner.v1.FragmentType
	2,  // 1: refiner.v1.RagChunk.fragments:type_name -> refiner.v1.RagFragment
	1,  // 2: refiner.v1.RefineRequest.messages:type_name -> refiner.v1.Message
	3,  // 3: refiner.v1.RefineRequest.rag_chunks:type_name -> refiner.v1.RagChunk
	5,  // 4: refiner.v1.RefineRequest.model:type_name -> refiner.v1.ModelConfig
	15, // 5: refiner.v1.StepAudit.details:type_name -> refiner.v1.StepAudit.DetailsEntry
	7,  // 6: refiner.v1.StepAudit.capabilities:type_name -> refiner.v1.ProcessorCapabilities
	8,  // 7: refiner.v1.StepAudit.semantic:type_name -> refiner.v1.StepSemanticAudit
	9,  // 8: refiner.v1.RefineResponse.audits:type_name -> refiner.v1.StepAudit
	4,  // 9: refiner.v1.RefineResponse.paged_chunks:type_name -> refiner.v1.PagedChunk
	16, // 10: refiner.v1.RefineResponse.metadata:type_name -> refiner.v1.RefineResponse.MetadataEntry
	17, // 11: refiner.v1.SummaryArtifact.created_at:type_name -> google.protobuf.Timestamp
	17, // 12: refiner.v1.SummaryArtifact.expires_at:type_name -> google.protobuf.Timestamp
	12, // 13: refiner.v1.StoredPage.summary_artifact:type_name -> refiner.v1.SummaryArtifact
	13, // 14: refiner.v1.PageInResponse.pages:type_name -> refiner.v1.StoredPage
	6,  // 15: refiner.v1.RefinerService.Refine:input_type -> refiner.v1.RefineRequest
	11, // 16: refiner.v1.RefinerService.PageIn:input_type -> refiner.v1.PageInRequest
	10, // 17: refiner.v1.RefinerService.Refine:output_type -> refiner.v1.RefineResponse
	14, // 18: refiner.v1.RefinerService.PageIn:output_type -> refiner.v1.PageInResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_refiner_proto_init() }
func file_api_refiner_proto_init() {
	if File_api_refiner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_refiner_proto_rawDesc), len(file_api_refiner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_refiner_proto_goTypes,
		DependencyIndexes: file_api_refiner_proto_depIdxs,
		EnumInfos:         file_api_refiner_proto_enumTypes,
		MessageInfos:      file_api_refiner_proto_msgTypes,
	}.Build()
	File_api_refiner_proto = out.File
	file_api_refiner_proto_goTypes = nil
	file_api_refiner_proto_depIdxs = nil
}
